### ISSUE TITLE
Support .bf animation files exports for ZT2

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_niftools_addon#129]
The .bf is a version of the .kf format with some specific optimisations, namely no header , data type changes and new block types. This should be supported by the plugin to allow the import and export of this file type.

Req : niftools/pyffi#1

**Comment by HENDRIX-ZT2** [comment]
I have the file format specification for BF files but never quite understood how to create new file types with pyffi... ;D

In general I think my pyffi-free implementation is better for the ZT2-exclusive formats (BFB models & BF animations):
- fully featured and tailored to that one file format
- super fast due to less overhead
- stable with 2.79

IMO there's no need to reinvent the wheel here, especially since demand for a second implementation seems to be very low to nonexistant. It's probably better to focus on the "core" NIF format.
