### ISSUE TITLE
error when importing

### ISSUE THREAD

**Issue by PoroUnited** [niftools/blender_niftools_addon#536]
no idea what this all means so i hope putting it here can get me some aid
(added the nif in question because i saw it being asked for in another post)

[eaueboots01.zip](https://github.com/niftools/blender_niftools_addon/files/9722307/eaueboots01.zip)
![aa484dd2653ed4b22d1f6195b71fba7d](https://user-images.githubusercontent.com/42877116/194246401-24753153-f555-4937-bcd5-144389dcdd52.png)

**Comment by Candoran2** [comment]
In your specific case, it appears to be happening because NifFormat.EPSILON is too large (or the determinant of that specific matrix is too small). There's no easy way to fix that for you right now. If you really want to try to fix it, you can do the following:

Open Blender's scripting layout, and in the Python Console type the following commands:
```python
from pyffi.formats.nif import NifFormat
NifFormat.EPSILON = 0.0001 * 0.0001
```

That should set the NifFormat.EPSILON to a sufficiently low value for your case to pass.

**Comment by Candoran2** [comment]
On our side, there's a couple ways to move forward with this:

- Make sure the determinant gets compared to the square of NifFormat.EPSILON (since determinants get computed by the multiplication of components its scale, and therefore its error tolerance, should be much lower/higher than that of individual components). In this specific case that alone would be enough to pass.
- Allow the user to adjust NifFormat.EPSILON - this can be done one of two ways. Either we add a separate setting for NifFormat's epsilon, or we always make it match the epsilon we already use in the plugin itself.

Note that the two solutions are not mutually exclusive.
@HENDRIX-ZT2 Thoughts?

**Comment by HENDRIX-ZT2** [comment]
I prefer a, squaring the determinant. But it sounds like the source matrix is faulty...?

**Comment by Candoran2** [comment]
> I prefer a, squaring the determinant. But it sounds like the source matrix is faulty...?

Yes and no. Looking into the nif, the scale for the skin transform is 0.044731, which is probably a mistake and why we haven't run into it before. However, it isn't technically wrong. A small scale will result in small matrix values, and therefore an even smaller determinant - which pyffi will then compare to EPSILON, and think it must be so small that the matrix has a determinant of 0 and can't be inversed, even though that isn't the case.

**Comment by Candoran2** [comment]
Fixed in https://github.com/Candoran2/new-pyffi/commit/555339fc393e5045676e5db09af73807b1d80d96
