### ISSUE TITLE
Animations are not imported correctly!

### ISSUE THREAD

**Issue by X4NDR0** [niftools/blender_niftools_addon#563]
I was trying to import nif file from game called "Divinity 2 DKS" and I found a problem.
Mesh and skeleton are imported correctly while animations are not.
Here it's how it looks : https://prnt.sc/Wez_hxKpkDUh

This is how it looks in "Rest pose" : https://prnt.sc/y_M3ZYMltTVM
NIF Model : https://www.sendspace.com/file/2c24rx

On some models some animations are working great but some are not.
Here is an example of that nif model : https://www.sendspace.com/file/8r40gr
You can check animations "Die_01" that one is not working properly, while "Hit_back" is working great.

It would be nice to fix this and cover this game too!

**Comment by Candoran2** [comment]
I think I've found the culprit. When importing with default values, the animations are indeed incorrect. However, when importing with scale=1.00, the animations appear to be correct. Most likely the apply_scale function for some of the animation blocks forget to adjust the translation values.

On the user side the obvious solution is to import with scale=1.00, and scale it yourself in Blender afterwards. Hopefully now the problem is identified, the fix should be relatively simple.

**Comment by HENDRIX-ZT2** [comment]
Yeah, scale is not propagated for some of the interpolator iirc.

I have long argued to remove the scale correction all together and make use of blender's unit system if needed

**Comment by Ghostwalker71** [comment]
@HENDRIX-ZT2 The only reason that the scale was added to the plugin was that Blender 2.49 could not handle the larger size of the nif meshes. That hasn't been an issue since about 2.6 so altering the scale of the nif serves no positive purpose and only injects rounding errors for vertex and node placement. If you can convince the team to abandon the scale alteration you can also discard some of the bone mapping that is only needed to save the original bone matrices to avoid gaps at the joints of the mesh parts due to the rounding errors injected by scale. The only issue with removing the scale alteration that I can think of is that you would need to alter the blender scene generation so that it properly set the view size to the original nif mesh size.
